import {
  Chakra_Petch,
  Inter,
  Poppins,
  Unbounded,
  Sora,
} from "next/font/google";

import "./globals.css";

const chakraPetch = Chakra_Petch({
  variable: "--font-chakraPetch",
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
  display: "swap",
});

const inter = Inter({
  variable: "--font-inter",
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
  display: "swap",
});

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  display: "swap",
});

const unbounded = Unbounded({
  variable: "--font-unbounded",
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
  display: "swap",
});

const sora = Sora({
  variable: "--font-sora",
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "DashBoard_Project",
  description: "Generated by create next app",
  icons: {
    icon: "/107.jpg",
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`
          ${chakraPetch.variable}
          ${inter.variable}
          ${poppins.variable}
          ${unbounded.variable}
          ${sora.variable}
          antialiased
        `}
      >
        <main>{children}</main>
      </body>
    </html>
  );
}
